# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wish_app.User'),
            preserve_default=False,
        ),
    ]
